# Generated by Django 2.2.5 on 2020-02-20 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='StyleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=2048)),
                ('content_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='painter_service.ContentImage')),
                ('style_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='painter_service.StyleImage')),
            ],
        ),
    ]
