# Generated by Django 2.2.5 on 2020-02-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painter_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='styleimage',
            name='name',
            field=models.CharField(default='Style', max_length=100),
        ),
    ]
