# Generated by Django 2.2.5 on 2020-02-20 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painter_service', '0006_painterrequest_requestpainting'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaintingCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='RequestPainting',
        ),
    ]
