# Generated by Django 2.2.5 on 2020-02-20 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('painter_service', '0007_auto_20200220_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestPainting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_image_url', models.CharField(max_length=2048)),
                ('chosen_by_user', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='painter_service.PaintingCollection')),
                ('painter_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='painter_service.PainterRequest')),
            ],
        ),
    ]
