# Generated by Django 2.2.5 on 2020-02-20 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painter_service', '0008_requestpainting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestpainting',
            name='collection',
        ),
        migrations.DeleteModel(
            name='PaintingCollection',
        ),
    ]
