# Generated by Django 2.2.5 on 2020-02-23 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='painterrequest',
            old_name='content_image_url',
            new_name='content_image_path',
        ),
        migrations.RenameField(
            model_name='requestpainting',
            old_name='generated_image_url',
            new_name='generated_image_path',
        ),
    ]
