# Generated by Django 2.2.5 on 2020-02-20 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('painter_service', '0001_initial'),
        ('client_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestPainting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_by_user', models.BooleanField(default=False)),
                ('date_generated', models.DateTimeField(auto_now_add=True)),
                ('generated_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='painter_service.GeneratedImage')),
                ('painter_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_service.PainterRequest')),
            ],
        ),
    ]
