# Generated by Django 2.2.5 on 2020-02-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_service', '0002_requestpainting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='painterrequest',
            name='is_fulfilled',
        ),
        migrations.AddField(
            model_name='painterrequest',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Processing'), (3, 'Completed'), (4, 'Failed')], default=1),
        ),
    ]
