# Generated by Django 2.2.5 on 2020-02-20 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('painter_service', '0004_auto_20200220_1114'),
        ('client_service', '0004_auto_20200220_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='PainterRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Processing'), (3, 'Completed'), (4, 'Failed')], default=1)),
                ('content_image_url', models.CharField(max_length=2048)),
                ('recipient_email', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestPainting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_by_user', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('generated_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='painter_service.GeneratedImage')),
                ('painter_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_service.PainterRequest')),
            ],
        ),
    ]
